site_name: SWAT-UQ
theme:
  name: material
  palette:
    scheme: light
  code:
    highlight_theme: monokai
  features:
    - navigation.indexes
    - navigation.language

plugins:
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Introduction: index.md
            - Tutorial:
              - SWAT-UQ-DEV: swat_uq_dev.md
              - SWAT-UQ-GUI: swat_uq_gui.md
            - Example Collection:
              - Example 1: example_runoff_calibration.md
              - Example 2: best_management_practices.md
        - locale: zh
          name: 中文
          build: true
          nav:
            - 介绍: index.md
            - 教程:
              - DEV版使用教程: swat_uq_dev.md
              - GUI版使用教程: swat_uq_gui.md
            - 示例集合:
              - 示例一：径流校准: example_runoff_calibration.md
              - 示例二：最佳工程管理: best_management_practices.md

extra_css:
  - css/nav_.css
  - css/head_.css
  - css/content_.css
  - css/table_.css

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

site_url: https://SWAT-UQ.readthedocs.io/
repo_url: https://github.com/smasky/SWAT-UQ

use_directory_urls: false

