site_name: SWAT-UQ
theme:
  name: material
  palette:
    scheme: light
  code:
    highlight_theme: monokai
  features:
    - navigation.indexes

nav:
  - Introduction: 'index.md'

extra_css:
  - css/nav_.css
  - css/head_.css
  - css/content_.css
  - css/table_.css

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

site_url: https://SWAT-UQ.readthedocs.io/
repo_url: https://github.com/smasky/SWAT-UQ

use_directory_urls: false

extra:
  static_path: docs